services:
  - type: web
    name: painel-dashway
    env: python
    plan: standard  # ou starter/pro, desde que tenha suporte a disco
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python painel_dash.py"
    disk:
      name: volume-json
      mountPath: /data
      sizeGB: 1
