services:
  - type: web
    name: painel-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    disk:
      name: volume-json
      mountPath: /data
      sizeGB: 1

  - type: background
    name: atualizador-automatico
    env: python
    startCommand: python agendador_06.py
    schedule: "0 0 * * *"  # todos os dias à meia-noite
    disk:
      name: volume-json
      mountPath: /data
