services:
  - type: web
    name: dashway-dashboard
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --timeout 300
    disk:
      name: volume-dados
      mountPath: /data
      sizeGB: 1

  - type: background
    name: dashway-atualizador
    env: python
    startCommand: python agendador_06.py
    schedule: "0 0 * * *"  # executa todos os dias à meia-noite
    disk:
      name: volume-dados
      mountPath: /data
