# render.yaml
services:
  - type: web
    name: dash_way_group
    ...
  - type: worker
    name: dash_way_worker
    runtime: python
    buildCommand: ""
    startCommand: "python inicializador_dados.py"
    envVars:
      - key: DATA_PATH
        value: /data
